- plugins/child_page_index.php
wp_reset_postdata(); をしないと、この後のクエリに影響が出る。
> add wp_reset_postdata(); after WP_Query loop

- inc/other-widget/widget-new-posts.php
VK 最新記事で複数投稿タイプを扱えるように widget-new-posts.php を編集しました。
（投稿タイプの欄でカンマ区切リで入力することで複数投稿タイプを指定可能に）
説明文は書き方がよくわからなかったので付加していません。
> VK 最新記事で複数投稿タイプを扱えるように

- inc/sns/function-sns-btns.php
Twitter ではなぜか半角縦棒 `|` がエンコードされずにエラーになっていたようなのでエンコードしました。
> 【確認待ち】sns タイトルに rawurlencode を適用（コピーでは解除）

- inc/wp-title/package/wp-title.php
https://wordpress.org/support/topic/inputtextarea%e3%81%a7%e3%82%a8%e3%82%b9%e3%82%b1%e3%83%bc%e3%83%97%e6%96%87%e5%ad%97%e3%81%8c%e5%a2%97%e6%ae%96%e3%81%99%e3%82%8b-2/
上記の件の修正が終わりました。
エスケープ文字を入力するのが個人的にはまれだと思うので上記で指摘された部分のみ修正しました。
[stripslashes](https://www.php.net/manual/ja/function.stripslashes.php) で何故か増えるバックスラッシュを消す処理をしています
> 【引き続き作業待ち】バックスラッシュが増殖するバグを修正

- inc/call-to-action/package/class-vk-call-to-action.php
- inc/contact-section/contact-section.php
- inc/google_analytics/google_analytics.php
- inc/insert-ads.php
- inc/sns/sns.php
https://wordpress.org/support/topic/inputtextarea%e3%81%a7%e3%82%a8%e3%82%b9%e3%82%b1%e3%83%bc%e3%83%97%e6%96%87%e5%ad%97%e3%81%8c%e5%a2%97%e6%ae%96%e3%81%99%e3%82%8b-2/
下記でエスケープ文字が増殖しないようにしました。
URL が入力されるべきところは URL が入力されるようにしました。
■トップページの<title>タグ
トップページの<title>タグ
■SNS Settings
facebookアプリケーションID
Facebook アクセストークン
Twitter ID
Follow me box > Follow me box の見出しテキスト
■Google Analytics設定
Google Analytics設定
■連絡先情報
メッセージ
電話番号
電話アイコン
営業時間
お問い合わせ先URL
お問い合わせボタンに表示するテキスト
お問い合わせボタンに表示するテキスト2（オプション）
お問い合わせボタンウィジェットに表示するテキスト
お問い合わせバナー画像
■Call To Action
表示場所（オプション）
■広告の挿入
Google自動広告 > サイト運営者ID
上記テキストエリア等で \m\n と入力し設定を保存しました。
上記テキストエリア等全てでエスケープ文字を含む文字列をと入力し設定を保存。
* プルしたか？
* ビルドしたか？
* composer …
> 【確認待ち】input,textareaでエスケープ文字が増殖する

- admin/admin.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/794
https://vws.vektor-inc.co.jp/forums/topic/exunit-activate-setting-warning
有効化設定画面で warning が表示されないようにしました。
add_menu_page の使い方が間違っていたのを修正しました。
https://developer.wordpress.org/reference/functions/add_menu_page/
有効化設定画面で warning が表示されないのを確認しました。
ExUnit の有効化設定画面を開いて Warning が表示されないのを確認する
* プルしたか？
* ビルドしたか？
> 【確認待ち】有効化設定画面で warning が表示されないように

- inc/google_analytics/ga_admin.php
- inc/google_analytics/ga_customizer.php
- inc/google_analytics/google_analytics.php
- readme.txt
[ Google Analyticsのタグはログイン時は出力しないでほしい #800 ](https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/800)
Google Analytics設定にチェックボックス「Disable tracking of logged in user」を追加し、ログインしている状態のときにもGoogle Analytics を出力するか？しないか？選べるようにしました
* プルしたか？
* ビルドしたか？
> 【確認待ち】Google Analyticsのタグはログイン時は出力しない

- inc/child-page-index/child-page-index.php
- inc/common-block.php
- inc/contact-section/contact-section.php
- inc/page-list-ancestor/page-list-ancestor.php
- inc/sitemap-page/sitemap-page.php
- inc/sns/function-sns-btns.php
- readme.txt
ExUnit内のブロックで共通余白を設定しても公開画面でクラス名が設定されない、もしくは編集画面でブロックにエラーが生じるため
関連 https://github.com/vektor-inc/vk-blocks-pro/pull/1105
共通のattribute変数に余白を追加
その変数を追加する関数名の変更
確認用HTML
```HTML
<h2>ExUnitのブロック一覧</h2>
```
1. VK BlocksとExUnitを有効化した環境を用意する
2. 配布済みバージョンでExUnitのブロックを配置
3. ExUnitのブロックの共通余白機能の挙動を確認
公開画面でクラス名が付かないor編集画面でエラーが発生する
4. このブランチでExUnitのブロックを配置し共通余白機能が通常のブロックと同様に同様に使用できることを確認
上記確認方法と同じ、他なにか気になる箇所があればご指摘お願いします。
---
* プルしたか？
* ビルドしたか？
> 【確認待ち】VK Blocksの余白設定をExUnit内のブロックに追加

- inc/child-page-index/child-page-index.php
- inc/contact-section/contact-section.php
- inc/page-list-ancestor/page-list-ancestor.php
- readme.txt
以下のプルリク確認中に見つかったクラス名の重複を修正
https://github.com/vektor-inc/vk-blocks-pro/pull/1149#issuecomment-1097856426
・子ページリスト
・お問い合わせ
・先祖階層からの子ページリスト
の追加CSS,非表示設定のクラス名の重複を調整
コアでも似たようなバグを修正した時にユニットテストなどは無かったのでテストは追加していません
https://github.com/WordPress/gutenberg/pull/39777
・子ページリスト
・お問い合わせ
・先祖階層からの子ページリスト
を配置して追加CSSのクラス名追加,非表示設定を追加
追加CSS、非表示設定のクラス名が重複して表示されないことを確認
---
* プルしたか？
* ビルドしたか？
> 【確認中】[ Child Page List / Contact section / Page list from ancestor ] クラス名の重複を調整

- inc/sns/function-sns-btns.php
- inc/sns/sns.php
- inc/sns/sns_admin.php
- readme.txt
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/712
* SNS ボタンをアクションフックを指定して出力できるように変更しました。
1. テーマを Lightning に変更
2. 設定画面で「lightning_entry_body_before」「lightning_comment_before」を改行区切りで入力
3. 任意の投稿の表示画面で SNS ボタンが２つ出力されているのを確認
1. テーマを Lightning に変更
2. 設定画面で「lightning_entry_body_before」「lightning_comment_before」を改行区切りで入力
3. 任意の投稿の表示画面で SNS ボタンが２つ出力されているのを確認
---
* プルしたか？
* ビルドしたか？
> 【確認待ち】アクションフックで SNS ボタンを出力できるように

- inc/template-tags/package/template-tags-veu.php
- readme.txt
- tests/test-get-common-options-default.php
- veu-packages.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/835
- 有効化設定の初期設定がブロックテーマの場合ブロックテーマ用の設定になるようにしました
- wp-env 環境で npx wp-env destroy 後に npx wp-env start を実行してから ExUnit > 有効化設定を確認しました
- その後 WordPress のバージョンを 5.8.4 にしてから同様に確認しました
wp-env 環境で npx wp-env destroy 後に npx wp-env start を実行した環境
- wp-env 環境で npx wp-env destroy 後に npx wp-env start を実行してから ExUnit > 有効化設定を確認
- その後 WordPress のバージョンを 5.8.4 にしてから同様に確認
---
* プルしたか？
* ビルドしたか？
> 【確認待ち】有効化設定の初期設定がブロックテーマの場合ブロックテーマ用の設定になるように 

- inc/call-to-action/package/blocks/index.php
- tests/test-cta.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/902 の追加対応
return 以前でエスケープ入れると
* 基本的には出力の直前でやるのが良いです。途中でやると、それこそ中途半端にエスケープされたり２重にされたりで脆弱性に繋がりやすいですね。by とろゆにさん
* テストの時に &amp;amp; とか書かないといけない by しずみさん and 僕
> [ CTA ] Change escape to only last / エスケープを return 直前だけに変更

- inc/call-to-action/package/blocks/index.php
- tests/test-cta.php
This reverts commit 0018dc53e9c0c96571cd3652e7d3c3fd3d0960ec.
esc_attr() を通さない場合、ブロックのCSS入力欄に
`" onmouseover="alert(/XSS/)" style="background:red;" `
と入れるとスタイルは wp_kses_post が通してしまうため、やはり esc_attr() を通す方式に戻し
> Revert "[ CTA ] Change escape to only last"

- admin/class-veu-metabox.php
- inc/wp-title/config.php
- readme.txt
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/915
そもそもカスタム投稿タイプで入力欄が表示されないのが不具合だった
→ 書きたいがいろいろ間に合わないので別途 
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/918
* ExUnit でカスタム投稿タイプを作成
* 記事の編集欄でタイトルを指定
* タイトルタグに反映される事を確認
> [ 不具合修正 ][ タイトルタグ書き換え ] カスタム投稿タイプで入力欄が表示されない不具合を修正 #915

- inc/sns/class-veu-metabox-sns-button.php
- inc/sns/function-sns-btns.php
- readme.txt
- tests/test-sns-btns.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1027
シェアボタンの非表示制御のチェックボックスは常に表示するように変更
> [ Bug fix ][ Share Button ] Changed to always display the checkbox for hiding the share button.

- composer.json
- composer.lock
- readme.txt
Font Awesome 5 の無駄なデータが残っていて All in One WP Migration などで容量を圧迫するためアップデート
VK Font Awesome Version をアップデート
> [ Update ][ Font Awesome ] Update font awesome 6.4.3 and delete Font Awesome 5

- .gitignore
- inc/post-type-manager/package/class.post-type-manager.php
- readme.txt
[[ カスタム投稿タイプマネージャー ] リライトをオフにするオプションを追加して欲しい by あんどうさん](https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1066)
- カスタム投稿タイプマネージャー の リライトをオフにするオプションを追加
⇒投稿タイプの設定項目の話なので省略
1. カスタム投稿タイプを適当に作成
2.  /news/%postname%/ にパーマリンクを設定
3. リライトが ON だと /news/event/%postname%/  になる
4. リライトが OFF だとリライトが一切発動しない
ローカル環境
1. カスタム投稿タイプを適当に作成
2.  /news/%postname%/ にパーマリンクを設定
3. リライトが ON だと /news/event/%postname%/  になる
4. リライトが OFF だとリライトが一切発動しない
---
* プルしたか？
* ビルドしたか？
> 【カスタム投稿タイプマネージャー 】リライトをオフにするオプションを追加

- inc/post-type-manager/package/class.post-type-manager.php
- readme.txt
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1066
* リライトの設定で with_front を false に指定できるように変更
* それに伴い旧パーマリンクの書き換え廃止
* カスタム分類のパーマリンクの書き換え指定UIも廃止し、カスタム投稿タイプのパーマリンクの書き換えを踏襲するように変更（一般ユーザーがカスタム分類毎に項目を指定する可能性は低い。設定項目が多いと初心者が混乱するため）
■ Before
■ After
■ Before
* 設定 > パーマリンク > カスタム構造 で news/%postname%/ に指定
* ExUnit のカスタム投稿タイプマネージャーでカスタム投稿タイプ event を作成
* カスタム投稿タイプ event の投稿の詳細ページの公開URLが /news/event/ になってしまう。
■ After
* ExUnit のカスタム投稿タイプマネージャーの投稿タイプ event の設定画面で、with_front を false に指定
* カスタム投稿タイプ event の投稿の詳細ページの公開URLが /event/ になる（newsを除外できる）事を確認
実装者に同じ
---
* プルしたか？
* ビルドしたか？
> [ Post Type Manager ] Change so that "with_front" can be specified as false in permalink settings

- assets/_scss/_contents_option_style.scss
- readme.txt
[ページ制作に役立つ便利なCSS設定](https://ex-unit.nagoya/ja/about/class)がSafariではArialがタイポしている関係で明朝体で表示されていました。
ページ制作に役立つ便利なCSS設定で使われているFAQのfont-family指定をArialに修正しました。
→タイポの修正なので省略
→タイポの修正なので省略
1. [ページ制作に役立つ便利なCSS設定](https://ex-unit.nagoya/ja/about/class)にあるFAQのHTMLをコピー
2. 編集画面でカスタムHTMLを使い1をペースト
3. SafariでQやAがArialになっていることを確認
1. [ページ制作に役立つ便利なCSS設定](https://ex-unit.nagoya/ja/about/class)にあるFAQのHTMLをコピーしてください。
2. 編集画面でカスタムHTMLを使い1をペーストしてください。
3. SafariでQやAがArialになっていることを確認してください。
---
* プルしたか？
* ビルドしたか？
> 【確認待ち】ページ制作に役立つ便利なCSS設定のFAQのfont-family指定をArialに修正

- inc/add_plugin_link_to_adminbar.php
- readme.txt
- tests/test-add-plugin-link-to-adminbar.php
- vkExUnit.php
https://vws.vektor-inc.co.jp/forums/topic/90184
WordPress 6.5 で公開画面の管理バーにプラグインページへのリンクが表示されるようになった。
その都合上 ExUnit が追加するプラグインへのリンクと合わせて二重で表示されるようになってしまった。
* WordPress 6.5 以上の公開画面の場合は管理バーにプラグインへのリンクを追加しないように変更
* ExUnit > 有効化設定 > 管理画面機能 で 「管理バーにプラグインリンク追加」が有効になっている事を確認
* WordPress 6.5  & マスターブランチで管理バーを見ると先に掲載のSSのように「プラグイン」が二つ表示される
* このブランチに切り替え
* プラグインのリンクは一つしか出力されない事を確認
* 管理画面側でも同様に プラグイン ページへのリンクが管理バーに追加される事を確認
---
* wp-content/plugins/vk-all-in-one-expansion-unit/ のディレクトリで `wp-env start`
* `npm run phpunit` を叩いてテストが通る事を確認
ローカルでよろしくお願いいたします。
実装者に同じ
---
* プルしたか？
* ビルドしたか？
> 公開画面側にプラグイン画面へのリンクを追加しないように変更

- inc/css-customize/css-customize-single.php
- inc/css-customize/css-customize.php
- readme.txt
- tests/test-css-customize.php
#1088
個別投稿や固定ページのカスタム CSS 、VK All in One Expansion Unit CSSカスタマイズでメディアクエリで使用する比較演算子の>、<、>=、<=をエスケープしないようにしました。
1. ブロックエディターでテキストを入力。
2. カスタムCSSで以下を追加し「公開」をクリック。
```
@media (width >= 1000px) {
p { color: red; }
}
@media (width <= 1000px) {
p { color: blue; }
}
```
3. フロントエンドで画面の幅を変えてcolorが変わることを確認。
4. 編集画面に戻り、カスタムCSSで以下に置き換え「更新」をクリック。
```
@media (width > 1000px) {
p { color: green; }
}
@media (width < 1000px) {
p { color: orange; }
}
```
5 . フロントエンドで画面の幅を変えてcolorが変わることを確認。
1. ダッシュボードから [ExUnit] > [カスタマイズCSS] に移動。
2. フォームに以下を追加し「CSSを保存する」をクリック。
```
@media (width >= 1000px) {
p { color: red; }
}
@media (width <= 1000px) {
p { color: blue; }
}
```
3. フロントエンドで画面の幅を変えてcolorが変わることを確認。
4. カスタマイズCSSに戻り、フォームに以下を置き換え「CSSを保存する」をクリック。 …
> [カスタム CSS] メディアクエリ演算子を保持

- inc/call-to-action/package/class-vk-call-to-action.php
- inc/call-to-action/package/view-actionbox.php
- tests/test-cta.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/1101 でエスケープを追加したが、
厳しすぎてかなり表示が崩れてしまう
* CTA 出力時の wp_kses の解除
* PHPUnitテスト追加
* 入力欄に使っていた wp_kses の allowed_html をメソッド使用に変更
* master に切り替え
* CTA に https://patterns.vektor-inc.co.jp/vk-patterns/cta-pr-contents-free-full-width/ を登録
* 固定ページなどで ↑ を表示 -> エスケープされる
* このブランチに切り替え
* 適切に表示される事を確認
その他コードに問題があるかどうか
---
* プルしたか？
* ビルドしたか？
> 【確認中】[ CTA ] ブロックで作成したCTAがエスケープされまくって崩れる不具合を修正

- tests/test-add-plugin-link-to-adminbar.php
- tests/test-article-structure.php
- tests/test-change-old-options.php
- tests/test-child-page-index.php
- tests/test-css-customize.php
- tests/test-cta-default-display.php
- tests/test-cta.php
- tests/test-get-common-options-default.php
- tests/test-icon-accessibility.php
- tests/test-insert-item-meta-box-display.php
- tests/test-isert-ads.php
- tests/test-make-ga-script.php
- tests/test-package_manager.php
- tests/test-page-list-ancestor.php
- tests/test-parent-meta-box-display.php
- tests/test-promotion-alert.php
- tests/test-sns-btn-style.php
- tests/test-sns-btns.php
- tests/test-sns-title.php
- tests/test-template-tags.php
- tests/test-website-structure.php
- tests/test-widget-btn.php
- tests/test-widget-new-post.php
- tests/test-widget-page.php
- tests/test-widget-profile.php
- tests/test-widget-title.php
- tests/test-wp-title.php
PHPUnit を走らせたときに表示されるデバッグが多くなりすぎて見にくいのでコメントアウトしました。
必要なときにコメントアウト解除すれば良いかなと。
> デバッグ用の出力が多くなりすぎで逆に見えなくなったのでコメントアウト

- admin/admin-active-setting-page.php
- inc/post-type-manager/package/class.post-type-manager.php
- readme.txt
- veu-packages.php
#1099 
- カスタム投稿タイプ設定に関する記事やベクトレへのリンクを含む通知やテキストリンクを追加しました。
- 有効化一覧の中にカスタム投稿タイプ設定に関する記事を入れるためにtarget="_blank"にできるように設定を変更しました。(veu-packages.php のarrayに`'target'  => '_blank',`がない場合は、テキストリンククリック後、リンクURLが同一タブで開きます。)
- 管理画面でのヘルプ通知を、サイトの言語設定に基づいて動的に切り替え、日本語設定時にのみ表示されるようにしました。
WordPressの言語設定が日本語の場合、以下を確認しました。
- ダッシュボードから ExUnit > 有効化 > カスタム投稿タイプマネージャーに「Learm more」が追加されていること&Learm moreをクリックすると別タブで https://ex-unit.nagoya/ja/about/custom_post_type_manager が表示されることを確認。
- カスタム投稿タイプ設定やカスタム投稿タイプ設定で新規に追加したカスタム投稿タイプの編集画面で、「Help and Documentation」のヘルプ通知ボックスが表示されていることを確認。
- 右上のxや通知を無視をクリックすると表示されなくなることを確認。(xの時はページを再読み込みするとヘルプ通知が表示されます。)
- Help and Documentationの中のリンクが以下と同じかを確認。
1. ExUnit …
> [ カスタム投稿タイプマネージャー ] 設定から解説記事やベクトレへのリンクを追加

- inc/promotion-alert/package/class-veu-promotion-alert.php
- tests/test-promotion-alert.php
広告アラートを表示するかどうかのメソッド名が get_display_condition になっているが、
返り値が bool なので is_display の方が WordPress の作法的にわかりやすい気がする
> [ 広告アラート ] get_display_condition() ->  is_display() に変更

- inc/promotion-alert/package/class-veu-promotion-alert.php
- tests/test-promotion-alert.php
get_alert_content() で純粋に中身だけ取得してテストしたかったが、中に is_display() が入っていてそこで非表示にされてしまって都合が悪かった
is_display()  の処理を get_alert_content()  の外に移動
> [ 広告アラート ][ リファクタリング ] 	get_alert_content() は中身だけ返すようにして表示・非表示は外で使うように移動

- admin/admin.php
- initialize.php
- readme.txt
まっさらな WordPress で有効化すると
```
Warning: Undefined array key "default" in /var/www/html/wp-includes/option.php on line 3177
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/option.php:3177) in /var/www/html/wp-admin/customize.php on line 130
```
が発生する
* initialize.php に記載してあった option値 vkExUnit_common_options の register_setting() を削除
そもそも vkExUnit_common_options は admin/admin.php で register_setting() してる
* `delete_option( 'vkExUnit_common_options' );` などで vkExUnit_common_options を一旦削除
* master ブランチ で ExUnit > 有効化設定にアクセス -> Warning が発生
* このブランチに切り替える -> Warning が消える
> [ Bug Fix ] Fixed a PHP error that occurs when the activation settings have never been saved.

- inc/other-widget/widget-taxonomies.php
- readme.txt
> [ Bug fix ][ Categories/Custom taxonomies list widget ] Display order translation

- composer.lock
- inc/nav-menu-class-custom/class-nav-menu-class-custom.php
- tests/test-nav-menu-class-custom.php
カスタム投稿タイプで他のカスタム投稿タイプのトップメニューなどに current-menu-ancestor クラスなどがついてしまったりするのでアクティブ以外のものを強制的に削除
> [ Navigation Menu Custom ] カスタム投稿タイプで誤動作修正

- inc/call-to-action/package/block/block.json
- inc/child-page-index/block/block.json
- inc/contact-section/block/block.json
- inc/page-list-ancestor/block/block.json
- inc/sitemap-page/block/block.json
- inc/sns/block/block.json
- readme.txt
https://github.com/vektor-inc/vk-blocks-pro/issues/2289#issuecomment-2446050765
blocks.json の apiVersion を 3 に変更することで、ズームアウトのトグルがエディターツールバーに常に表示されるよう修正しました。
今回はバージョン変更によって解消されたため上記のリンクにある、
> メタボックスを利用しない（プラグインサイドバー or ブロックベースメタボックスで展開する）
という部分を変更していません。
https://github.com/user-attachments/assets/32ff1b37-1ae4-4ec6-8aa6-ca8a2ed91bfd
1. プラグインで「VK All in One Expansion Unit」 だけを有効にする。
2. 新規固定ページで以下のブロックを全て追加する。
3. エディターツールバーにズームアウトのトグルや「ドラッグしてサイズ変更」が常に表示されており、さらに機能していることを確認。
4. 保存し、フロントエンドで全てのブロックが表示、機能していることを確認。
実装者と同じ確認を行ってください。
その他気になる点があれば適宜ご確認ください。
---
* プルしたか？
* ビルドしたか？
> エディターツールバーにズームアウトのトグルが常に表示されない不具合を修正

- inc/call-to-action/package/class-vk-call-to-action.php
- readme.txt
- tests/test-cta.php
#1170 
- 不必要なwp_kses_post() を削除し、不要なエスケープ処理を排除。
- safe_kses_post() の iframe 処理を最適化し、iframe がない場合の不要な処理を削減。
1. master ブランチでCTAで新規ページを追加し、以下のブロックを設定。
- グループブロックで背景画像を設定。
- 段落ブロックで一部のテキストを選択し、ハイライトで文字色だけを変更。
- Google Map をiframeタグで埋め込み。
- https://www.vektor-inc.co.jp/ をiframeタグで埋め込み。
2. ExUnit > メイン設定 > Call To Action で1で作成したページを設定
3. フロントエンドで以下になってしまっていることを確認。
- グループブロックで背景画像が消えてしまっている。
- ハイライト設定した背景色が黄色くなってしまっている。
- (Google Map はiframeタグで表示される。)
- (https://www.vektor-inc.co.jp/ は表示されない。)
4. fix/cta/mark に切り替え、1の編集画面と同じ表示になっていることを確認。
- グループブロックで背景画像が表示されている。
- ハイライト設定した背景色が黄色くならない。
- (Google Map はiframeタグで表示される。)
- (https://www.vektor-inc.co.jp/ は表示されない。) …
> [ CTA ] 一部のcssがエスケープされる現象を修正しました

- inc/sns/block/src/edit.js
- inc/sns/sns.php
- inc/sns/sns_admin.php
- readme.txt
#1162 
ソーシャルボタンのスタイル設定（ボタンの色や背景なしのオプション）を ExUnit のメイン設定画面（ExUnit > メイン設定 > SNS Setting）からも変更できるようにしました。
ExUnit > メイン設定 > SNS Setting 
シェアボタンブロック
ExUnit > メイン設定 > SNS Setting
シェアボタンブロック
1. 管理画面の ExUnit > メイン設定 > SNS Settingから 背景なし のチェックとボタンの色のカラーピッカーが出ていることを確認しました。
2. 1の設定をしたら、シェアボタンの色や背景の有無が変わることを確認しました。
3. 外観 > カスタマイズ > ExUnit 設定 > SNS 設定 にある 背景なし のチェックとボタンの色のカラーピッカーの設定が1の保存値と同じことを確認しました。
4. カスタマイザーから、背景なし のチェックとボタンの色のカラーピッカーの設定を保存したとき、 ExUnit > メイン設定 > SNS Settingにも反映されていることを確認しました。
5. 4の設定に基づいてシェアボタンの色や背景の有無が変わることを確認しました。
6. ExUnit > メイン設定 > SNS Settingから カラーピッカーのテキスト入力欄で16進法以外のテキストを入力すると空になるようにしました。
実装者と同じ確認を行ってください。 …
> [シェアボタン] ソーシャルボタンのスタイル設定（色や背景なし）をExUnitのメイン設定からでも変更できるようにしました

- inc/sns/function-sns-btns.php
- inc/sns/sns_admin.php
- readme.txt
- tests/test-sns-btns.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1177
- メイン設定画面で , 区切りで保存されている値（ vkExUnit_sns_options[snsBtn_ignorePosts] ）がある場合、カスタムフィールドでの保存値に変換
- メイン設定画面から入力UIの削除
- シェアボタン表示側で vkExUnit_sns_options[snsBtn_ignorePosts] に該当する場合は非表示にする処理があるが、不要になるため削除
- テストもそのあたり不要になるので削除
1. master ブランチでExUnit の SNS Settings の シェアボタンを表示しない投稿のID に既存の投稿 ID をカンマ区切りで入力して保存
2. このブランチに切り替えてブラウザを再読み込み（一応）したあと設定した投稿 ID の記事をの編集画面に移動
3. 記事編集画面の ExUnit のシェアボタンの非表示設定のソーシャルボタンを表示しないにチェックが入っているのを確認
4. ExUnit の設定の SNS Settings の シェアボタンを表示しない投稿のID が存在しないことを確認
5. npm run phpunit
開発環境
1. master ブランチでExUnit の SNS Settings の シェアボタンを表示しない投稿のID に既存の投稿 ID をカンマ区切りで入力して保存
2. このブランチに切り替えてブラウザを再読み込み（一応）したあと設定した投稿 …
> メイン設定画面の SNS の非表示設定を削除

- inc/call-to-action/package/assets/_scss/style.scss
- inc/call-to-action/package/block/index.php
- readme.txt
#1183 
元々 enqueue_block_assets で style.css を読み込む処理が master には存在していなかったため、CTA ブロックを「従来のレイアウトを使用する」に設定した際に、編集画面でスタイルが適用されてませんでした。
Lightining、X-T9、TT5で確認しました。
1. `master`でカスタム投稿のCTAで「従来のレイアウトを使用する」に設定したCTAを保存
2. 固定ページの編集画面でCTAブロックを置いた時にスタイルが適用されないことを確認
3. `fix/cta/editor/css`に切り替え`npm run build`
4. 固定ページの編集画面でCTAブロックを置いた時にスタイルが適用されることを確認
(Lightningの場合、CTAで使っているクラス名とテーマで使っているクラス名が被っている関係で、編集画面では表示が異なっている部分があります。テーマ側での対応をお願いいたします。)
5. フロントエンドでの表示に影響が出ていないことを確認(二重でCSSが読み込まれていないことも確認)
6. カスタム投稿のCTAでブロックエディタのCTAを作って保存し、固定ページの編集画面でそのCTAをCTAブロックに設定した時、スタイルの読み込みの影響で崩れたり表示がフロントエンドと同一であることを確認
実装者と同じ確認を行ってください。
他にも気になるところがあったら確認してください。
---
* プルしたか？
* …
> 従来のレイアウトの CTA のスタイルが編集画面に当たらないのを修正

- inc/sns/sns.php
- readme.txt
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1190
- SNS が原因で ExUnit Main Setting で Warning が出ないようにしました。
- ExUnit Main Setting の SNS の欄で Warning が出ないこと
- ExUnit Main Setting の SNS の欄で全て空欄にして保存しても Warning が出ないこと
- ExUnit Main Setting の SNS の欄を適当に埋めて値が保存されていること
上記を確認しました。
ローカル環境
- ExUnit Main Setting の SNS の欄で Warning が出ないこと
- ExUnit Main Setting の SNS の欄で全て空欄にして保存しても Warning が出ないこと
- ExUnit Main Setting の SNS の欄を適当に埋めて値が保存されていること
上記を確認お願いします。
---
* プルしたか？
* ビルドしたか？
> [ Bug fix ][ SNS ] ExUnit Main Setting の Warning に対処

- inc/post-type-manager/package/class.post-type-manager.php
- readme.txt
配信中の最新のカスタム投稿タイプ設定で埋め込み設定（任意）にチェックを入れても保存できませんでした。
チェックを付けて保存しても、保存後にチェックが外れてしまっていた原因は、
チェック時に `'true'` を保存していたため、内部的には `is_embeddable = true（埋め込みOK）` と解釈されてしまい、
チェックボックスが「外れて表示される」という逆転現象が起きていました。
本来このチェックボックスは「埋め込みを無効にしたいときにチェックを入れる」仕様なので、
チェックされていたら `'false'` を保存し、`('false' !== $is_embeddable)` によって
`is_embeddable = false` と解釈されるように修正しました。
以前のプルリクでは直していたのですが、途中バージョン変更をする際に古いデータで書き換えていたかもしれません。
すみません。
1. カスタム投稿タイプ設定で「外部サイトからの埋め込み（oEmbed）を許可しない」がチェックでき、保存後もチェックのままになっていることを確認
2. カスタム投稿タイプ設定で「外部サイトからの埋め込み（oEmbed）を許可しない」がチェックを外し、保存後もチェックが外れていることを確認
3. 以下のサイトでチェックの有無によって埋め込めるか否かを確認
※ 以前以下のドメインのサイトを埋め込みで貼り付けたことのあるサイトではキャッシュで昔の情報が参照される恐れがあります。
- 外部サイトからの埋め込み（oEmbed）を許可しないチェックをした投稿タイプ …
> [ 不具合修正 ][ カスタム投稿タイプ設定 ] 埋め込み設定のチェックボックスにチェックを入れても保存されないのを解消

- inc/sns/function-sns-btns.php
- readme.txt
#1211 
Snow Monkey Forms の <form> 要素内部に veu_socialSet クラスのシェアボタンが混入してしまう不具合を修正しました。
Snow Monkey Forms 以外でも、Formタグに入ってしまうことがあるかもしれないため、以下2点の対策を `veu_add_sns_btns() `に追加しました。
1. フォーム内混入の削除処理
`the_content` に挿入された シェアボタンが `<form>`タグ内に入り込むことを避けるため、`</form>` タグの位置を特定し、その範囲内から `veu_socialSet` を含む`<div> `を削除する処理を追加。
これまでは条件分岐のみで`the_content`に入るか否かを決めていたが、Formでは対応が難しかったため、自動挿入の時には `veu_socialSet-auto` というクラスを追加して、そのクラスが入ったシェアボタンを削除するように動作。
2. メインループ・メインクエリでない場合の挿入防止
シェアボタンが本文の前か後に入るのが前提のため、意図せずthe_contentが呼び出されている場合は挿入を防止するようにしました。
- in_the_loop() && is_main_query() を通過しない場合は、シェアボタンを追加しないように制御。
- フィルターフック veu_sns_btns_check_mainloop によって開発者が任意に条件を緩和できるように設計。
ExUnit > メイン設定 > SNS > ソーシャルボタン …
> [ 不具合修正 ][ シェアボタン ] Snow Monky Forms で Form タグの中に表示されてしまうシェアボタンを削除するようにしました

- inc/default-thumbnail/default-thumbnail.php
- readme.txt
- tests/test-default-thumbnail.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1236
*  `has_post_thumbnail`フィルターのパラメータ修正：https://developer.wordpress.org/reference/hooks/has_post_thumbnail/
* `$has_thumbnail`、`$post`、`$thumbnail_id`の3つが最新
* `$thumbnail_id`はパラメータの値を参照
* `post_thumbnail_id`フィルターを追加
* デフォルトサムネイル設定があればその値を返却
* デフォルトサムネイル設定がなければフィルターのパラメータをそのまま返却
* デフォルトサムネイル設定に関するテストケースの追加
* `post_thumbnail_html`
* `has_post_thumbnail`
* `post_thumbnail_id `
---
* プルしたか？
* ビルドしたか？
> [デフォルトアイキャッチ] 他プラグインとの組み合わせで問題となるケースがある
