_scss/style.scss, css/style.css, css/style_in_bs.css, plugins/other_widget/js/widget-3pr-uploader.js, plugins/other_widget/js/widget-prof-uploader.js, plugins/other_widget/widget-3pr-area.php, plugins/other_widget/widget-profile.php
=> Change other

plugins/sns/function_follow.php, plugins/sns/sns.php, plugins/sns/sns_admin.php
コンテンツ下にフックで追加している follow me 部分をオフに出来るように #27
=> コンテンツ下にフックで追加している follow me 部分をオフに出来るように #27

plugins/sns/function_meta_box.php, plugins/sns/function_og.php, plugins/sns/function_twitterCard.php, plugins/sns/sns.php
VK_最近の投稿 ウィジェットでカテゴリーを指定可能にする #45
=> Sns customtitle

plugins/sns/function_follow.php
=> [ follow me box ] feedlyのボタン追加

js/master.js
【参考】Hatena Bookmark: https://blog.hinaloe.net/2015/08/15/hatena-bookmark-api-on-ssl/
=> [ SNS Button ] snsCount のSSLページ対応化

plugins/other_widget/widget-profile.php
[ プロフィールウィジェット ] 画像の設定がない時に img タグが出力されてしまわないよう修正
=> [ プロフィールウィジェット ] 画像の設定がない時に img タグが出力されてしまわないよう修正

gulpfile.js, package.json
- package.jsonの追加
- gulpfileにcompileタスクの追加
=> [gulp] gulpfileの最適化

plugins/call_to_action/call_to_action.php, plugins/call_to_action/class.call_to_action.php, plugins/call_to_action/widget.call_to_action.php, plugins/child_page_index.php
=> [ CTA ] ウィジェットでも設置出来るようにする #155

plugins/other_widget/other_widget.php, plugins/other_widget/widget-banner.php
=> [ バナーウィジェット ] 新規機能追加

plugins/child_page_index.php, plugins/pageList_ancestor.php
=> [bugfix] 不要なHTML出力の抑制 #157

plugins/other_widget/widget-new-posts.php
=> [ 最新の記事ウィジェット ] 更新日順 が選択出来るように #153

plugins/other_widget/widget-3pr-area.php, plugins/other_widget/widget-pr-blocks.php
=> [ VK_3PRウィジェット ] リンクを別ウィンドウ指定も出来るように

plugins/other_widget/widget-banner.php
=>  Edit New issue [ バナーウィジェット ] メディアのタイトルと代替テキストが反映されるように

package_manager.php, plugins/call_to_action/class.call_to_action.php, plugins/contact_section.php, plugins/google_analytics/google_analytics.php, plugins/icons.php, plugins/insert_ads.php, plugins/meta_description.php, plugins/meta_keyword.php, plugins/sitemap_page/sitemap_page.php, plugins/sns/sns.php, plugins/wp_title.php
=> [ 管理バー ] 管理バーの メイン設定 の子メニューが公開画面でも出るようにする 

initialize.php, vkExUnit.php
=> [ 機能追加 ] 推奨外バージョンのPHP使用時のプラグイン無効化 

packages.php, plugins/bootstrap.php, uninstaller.php
=> Lightning以外でも使いやすいようにキーカラー設定とボタンclassなどの出力

plugins/other_widget/widget-profile.php
=> #224 profile widget

plugins/other_widget/widget-taxonomies.php
=> [ カスタム分類ウィジェット ] 投稿の無いタームを表示するかどうかの選択を可能に

plugins/sns/function_snsBtns.php, plugins/sns/sns.php, plugins/sns/sns_admin.php
=> [ SNSボタン ] 表示するボタンを選択出来るようにする

plugins/call-to-action/class-vk-call-to-action.php, plugins/call-to-action/view-adminsetting.php
related: replace while-list-eash to foreach #289
=> replace each to foreach

plugins/other_widget/widget-page.php
=> #275　固定ページリストを管理順・階層を維持して表示

plugins/google_analytics/ga_customizer.php, plugins/google_analytics/google_analytics.php
=> #298 [ GA設定 ] カスタマイザー実装

plugins/css_customize/css_customize.php, plugins/css_customize/css_customize_single.php
=> [ #341 ][ ページ固有のカスタムCSS機能 ] 新規追加

inc/contactform7-asset-optimize.php, veu-packages.php
=> Contact Form 7のアセット出力制御パッケージの追加

admin/admin-main-setting-page.php, inc/common-block.php, inc/noindex/noindex.php, inc/other-widget/widget-new-posts.php
下記エラーを修正しました。
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/632
=> PHP 8.0.3 上での Notice を修正

inc/vk-css-optimize/package/class-vk-css-optimize.php
=> CSS 最適化モジュールを更新

.gitignore, inc/vk-blocks/package/vk-blocks-functions.php, veu-package-manager.php
【5.8対応】DeprecatedなどのWarningが出るのを修正しました。
=> 【5.8対応】DeprecatedなどのWarningが出るのを修正

inc/call-to-action/package/view-actionbox.php
CTAの「従来のレイアウトを使用する」場合のタイトルを修正しました。
=> 【確認待ち】CTA「従来のレイアウトを使用する」場合のタイトルを修正

inc/sns/function-sns-btns.php, inc/sns/sns_customizer.php
- カスタマイザーの Line ボタンが表示されなかったのを修正
- カスタマイザーの SNS ボタンを表示するか否かの選択肢で画面が切り替わるよう修正
=> 【確認待ち】SNS のカスタマイザーの挙動を修正

inc/sns/function_follow.php
変更箇所で Trying to access array offset on value of type bool が表示されましたので修正しました。
=> 【確認待ち】Trying to access array offset on value of type bool を修正

inc/sns/sns.php, tests/test-sns-title.php
OGP タイトルの処理を変更しテストも追加しました。
npm run phpunit は通過済みです。
=> 【確認待ち】OGP タイトルの処理を変更

inc/other-widget/class-veu-other-widget-admin-control.php, inc/other-widget/template/admin_setting.php, readme.txt
有効化設定のウィジェットだけ無効化できなかったので無効化できるようにしました。
ウィジェット設定の上部に input-hidden を追加しそれをトリガーにウィジェットの変更が発動するようにしました。
（enable_only ってなんでしたっけ？）
=> 【確認中】有効化設定で全て無効化できるように

admin/admin.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/797
不要なカンマを削除
* プルしたか？
* ビルドしたか？
=> 【確認待ち】不要なカンマを削除

inc/post-type-manager/package/class.post-type-manager.php, readme.txt
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/823
=> Fix/custom post type manager/fix translate

admin/admin.php, inc/other-widget/widget-3pr-area.php, inc/other-widget/widget-pr-blocks.php, inc/other-widget/widget-profile.php, readme.txt
https://vws.vektor-inc.co.jp/forums/topic/welcart%E3%81%AE%E5%95%86%E5%93%81%E3%82%A2%E3%82%A4%E3%82%AD%E3%83%A3%E3%83%83%E3%83%81%E7%94%BB%E5%83%8F%E3%81%8C%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E3%81%AA%E3%81%84
=> [ 不具合修正 ] WelCart の商品登録画面でアイキャッチ画像が登録できない不具合を修正

inc/article-structure-data/class-vk-article-structure-data.php, readme.txt
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/862
* タイプミスによって発生した、ユーザー情報内の構造化データを変更し保存した際に発生する不具合を修正しました。
- レビュワー向けの確認方法と同様です。
- ユーザー情報編集から構造化データの項目を編集し、保存
- `Warning: call_user_func_array()`などのエラーがでず、正常に保存されていることを確認 
---
* プルしたか？
* ビルドしたか？
=> 【確認待ち】【構造化データ出力】ユーザー情報内の構造化データを保存した際に発生する不具合を修正

inc/google_analytics/ga_admin.php, inc/google_analytics/ga_customizer.php, inc/google_analytics/google_analytics.php, readme.txt, tests/test-make-ga-script.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/866
- GA4 と UA の両方のタグを出力できるように変更
- タグは gtag.js に統一
- 古いオプションは削除
- npm run phpunit で出力されるテストが可能
- 実際に設定しページのソースコードを見て表示されているのを確認
- npm run phpunit で出力されるテストが正常に稼働しているか
- 実際に設定しページのソースコードを見て表示されているか
---
* プルしたか？
* ビルドしたか？
=> 【石川確認中】Google Analytics のコード修正

.phpunit.xml, tests/test-head-title.php
トップページ用のPHPUnitテストを追加しやすくするようにリファクタリング
=> [ リファクタリング ] タイトル書き換えの PHPUnit テストのリファクタリング

inc/contact-section/customizer.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/833
- カスタマイザーの該当部分のサニタイズを sanitize_text_field から esc_url に変更しました。
⇒ カスタマイザーで保存できるかできないかの問題なのでとりあえずなしで。
1. 外観>カスタマイズ>ExUnit設定>お問い合わせ情報 と進む
2. お問い合わせ先URL に https://demo.dev3.biz/lightning-g3-pro/%e3%81%8a%e5%95%8f%e3%81%84%e5%90%88%e3%82%8f%e3%81%9b/ を入れても保存できるか確認
以上を確認しました。
1. 外観>カスタマイズ>ExUnit設定>お問い合わせ情報 と進む
2. お問い合わせ先URL に https://demo.dev3.biz/lightning-g3-pro/%e3%81%8a%e5%95%8f%e3%81%84%e5%90%88%e3%82%8f%e3%81%9b/ を入れても保存できるか確認
以上を確認お願いします。。
---
* プルしたか？
* ビルドしたか？
=> 【確認待ち】外観>カスタマイズ>ExUnit設定>お問い合わせ情報>お問い合わせ先URL のサニタイズ変更

tests/test-wp-title.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/918
* テストファイル名を変更し、テスト内容にカスタム投稿タイプを追加しました。
テストの追加のみなので書いていません。
テストの追加のみなので省略しました。
* テストがこれまで通り正常に通ることを確認しました。
* テストがこれまで通り正常に通ることを確認しました。
---
* プルしたか？
* ビルドしたか？
=> テストファイル名変更とカスタム投稿タイプのテストを追加

inc/call-to-action/package/block/index.php, inc/child-page-index/block/index.php, inc/contact-section/block/index.php, inc/page-list-ancestor/block/index.php, inc/sitemap-page/block/index.php, inc/sns/block/index.php, readme.txt
なんとなく
- wp_set_script_translations の使用箇所を修正
⇒ リリースしないと確認不可
=> 翻訳関数の設置場所の変更のみなので省略
- 実際にリリースしないとなんとも言えません
- 一応 PHP のエラーが出ないことは GitHub Action で確認済み
リリースしないと確認不可
- 実際にリリースしないとなんとも言えません
---
* プルしたか？
* ビルドしたか？
=> 【確認待ち】翻訳が反映されないのを修正（？）

inc/sitemap-page/sitemap-page.php, readme.txt
⇒石川さんに聞いたらスルーで OK とのこと
PHP 8.2 の管渠医で固定ページを１つ除外した状態でエラーが出ないことを確認しました。
ローカル環境
PHP 8.2 の管渠医で固定ページを１つ除外した状態でエラーが出ないことを確認お願いします。
---
* プルしたか？
* ビルドしたか？
=> 【確認待ち】サイトマップの mb_convert_kana のエラーを修正

inc/other-widget/widget-new-posts.php, readme.txt
https://wordpress.org/support/topic/undefined-array-key-id-2/
=> [ Bug fix ][ Nwe post widget ] Fix PHP Error

inc/sns/sns.php, readme.txt
js のパスが途中で // になる。
通常問題ないが Shifter など特定環境では読み込みに失敗する
パスの修正
=> [ Bug fix ][ Share button ] Fix js file path ( // -> / )

inc/sns/block/index.php, inc/sns/icons/style.css, readme.txt
- サイトエディタで SNS のアイコンが表示されるように
- サイトエディタで SNS のアイコンが表示されるように
⇒ SNS 用のアイコンをサイトエディタで読み込むようにしただけなので省略
サイトエディタで Share ボタンブロックを設置してアイコンが表示されているのを確認しました
Local
サイトエディタで Share ボタンブロックを設置してアイコンが表示されているのを確認お願いします。
---
* プルしたか？
* ビルドしたか？
=> 【2人目確認中】サイトエディタで SNS のアイコンが表示されるように

composer.json, composer.lock, readme.txt
チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
https://vws.vektor-inc.co.jp/forums/topic/admin-windows-local-path
どういう変更をしたか？
パスのURL置換部分をwp_normalize_path() を使って修正
=> [ Bug fix ][ VK Admin ] Fixed problem of filepath on Windows local environment.

package.json, tests/e2e/cta.spec.ts
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/997
- Playwright のテストを修正
⇒テストを修正しただけなので省略
npx wp-env clean && npx playwright test --trace on --project=chromium
ローカル環境
npx wp-env clean && npx playwright test --trace on --project=chromium
---
* プルしたか？
* ビルドしたか？
=> 【確認待ち】Playwright のテストが通るように

inc/template-tags/package/template-tags.php, readme.txt
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1001
- do_blocks と do_shortcode は似たもの同士なので do_blocks を削除
⇒ 動的ブロックの展開をやめただけなので省略
- 該当データで投稿本文が消失しないのを確認
ローカル環境
- 該当データで投稿本文が消失しないのを確認
---
* プルしたか？
* ビルドしたか？
=> 【確認待ち】抜粋を修正

composer.json, composer.lock, inc/template-tags/package/template-tags-veu.php, readme.txt, veu-packages.php
テーマ選択画面でブロックテーマのプレビューをしようとすると Fatal error になる
関連
https://github.com/vektor-inc/vk-blocks-pro/pull/1789/files
* Fatal Error を引き起こす vk css optimize のライブラリをアップデート
* 同様の理由で不具合を引き起こすコードを修正
→ vk css optimize ライブラリ側で書かれているので省略
* ExUnit -> 有効化設定で CSS 最適化 が無効化されている事を確認
* develop ブランチで 外観 > テーマ で TT2 をプレビューで fatal error が発生する事を確認
* このブランチに切り替えて Fatal error が解消する事を確認
* ExUnit -> 有効化設定で CSS 最適化 を有効にして同じプレビューで fatal error が発生する事を確認
* composer install して解消される事を確認
ローカルでよろしくお願いいたします。
実装者に同じ
---
* プルしたか？
* ビルドしたか？
=> 【確認待ち】テーマ選択画面でブロックテーマのプレビューをしようとすると Fatal error になる不具合を修正

inc/promotion-alert.php, readme.txt, tests/test-promotion-alert.php
アラートテキスト と アラートコンテンツ だと関係性がわかりにくい
アラートコンテンツ の表記を カスタムアラートコンテント に変更
---
* プルしたか？
* ビルドしたか？
=> 「アラートコンテンツ」の表記を「カスタムアラートコンテント」に変更

inc/sns/function-sns-btns.php, readme.txt, tests/test-sns-btns.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1020
- SNS のシェアボタンの表示ロジックを修正
1. ソーシャルボタンの自動挿入を有効化
2. 適当に投稿タイプ「投稿」で記事を作成
3. 何もしない状態だと上記投稿で SNS のシェアボタンが表示されるのを確認 
4. シェアボタンを表示しない投稿タイプ「投稿」にチェックを入れて保存
5. 例の投稿で表示されなくなるのを確認
6. ②の状態に戻す
7. 「シェアボタンを表示しない投稿のID」に例の投稿の ID を入力
8. 例の投稿で表示されなくなるのを確認
9. 「シェアボタンを表示しない投稿のID」に例の投稿の IDとカンマと投稿が存在する適当な数字を入力
10. 例の投稿で表示されないままなのを確認
11. ②の状態に戻す
12. 例の投稿で「ソーシャルボタンを表示しない」にチェックを入れる
13. 例の投稿で表示されないのを確認
14. 表示場所に lightning_comment_before を指定
15. 3~13 を繰り返して同じ結果になるのを確認
ローカル環境
1. ソーシャルボタンの自動挿入を有効化
2. 適当に投稿タイプ「投稿」で記事を作成
3. 何もしない状態だと上記投稿で SNS のシェアボタンが表示されるのを確認 
4. シェアボタンを表示しない投稿タイプ「投稿」にチェックを入れて保存
5. 例の投稿で表示されなくなるのを確認
6. ②の状態に戻す
7. …
=> 【確認待ち】SNS のシェアボタンの表示ロジックを修正

inc/footer-copyright-change.php, readme.txt
違法なサイトで Vektor,Inc. のコピーライトになると面倒なので、公式ディレクトリだけに変更
=> [ Specification Change ] Change Footer Copyright

inc/promotion-alert.php, readme.txt
フォーラム
広告アラートの投稿タイプのチェックボックスに不備があったのを修正しました。
⇒チェックボックスの内容なので省略
1. 投稿タイプ「投稿」で広告アラートを表示するように設定を変更
2. 投稿タイプ「投稿」で新規投稿を作成した後広告アラートの設定を「共通」のまま公開
3. 広告アラートが表示されるのを確認
4.  投稿タイプのチェックボックスの部分のソースコードを見て不備がないことを確認
ローカル環境
1. 投稿タイプ「投稿」で広告アラートを表示するように設定を変更
2. 投稿タイプ「投稿」で新規投稿を作成した後広告アラートの設定を「共通」のまま公開
3. 広告アラートが表示されるのを確認
4.  投稿タイプのチェックボックスの部分のソースコードを見て不備がないことを確認
---
* プルしたか？
* ビルドしたか？
=> 【2人目確認中】広告アラートの投稿タイプのチェックボックスを修正

composer.json, composer.lock, readme.txt
https://github.com/vektor-inc/vk-css-optimize/pull/15
=> [ Bug Fix ] Update CSS Optimizer 0.2.2

inc/other-widget/widget-page.php, readme.txt
-  [VK All in One Expansion Unitのエラー表示が出ます](https://vws.vektor-inc.co.jp/forums/topic/vk-all-in-one-expansion-unit%e3%81%ae%e3%82%a8%e3%83%a9%e3%83%bc%e8%a1%a8%e7%a4%ba%e3%81%8c%e5%87%ba%e3%81%be%e3%81%99)
- 上記の Warning が出ないように
⇒ Warning の解消のみで表示内容には変更がないため省略
1. VK 固定ページ本文を設置
2. 上記で設定した固定ページを削除
3. master ブランチだと Warning が表示 / このブランチだと Warning が表示されない
ローカル環境
1. VK 固定ページ本文を設置
2. 上記で設定した固定ページを削除
3. master ブランチだと Warning が表示 / このブランチだと Warning が表示されない
---
* プルしたか？
* ビルドしたか？
=> VK 固定ページ本文で設定した固定ページを完全削除しても Warning が出ないように

inc/contact-section/contact-section.php, readme.txt
=> [ Bug Fix ][ Contact Section ] Fixed an issue where icons do not display when input in <i> tag format. 

inc/post-type-manager/package/class.post-type-manager.php, readme.txt
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1068
カスタムフィールドをサポート
---
* プルしたか？
* ビルドしたか？
=> [ Add setting ][ Post Type Manager ] Add a custom field setting.

inc/vk-google-tag-manager/package/class-vk-google-tag-manager.php, readme.txt
#1091
* GTMスニペットタグ(noscriptタグ)のiframe要素にtitle属性を追加しました
Google Tag Manager (noscript) として出力 iframe タグに下記の title 属性が付いているか
`title="Google Tag Manager (noscript)"`
---
* プルしたか？
* ビルドしたか？
=> 【2人目確認待ち】[Google タグマネージャー]iframe要素にtitle属性を追加

inc/other-widget/widget-3pr-area.php
=> Bug fix wp_kses_post() typo

inc/call-to-action/package/class-vk-call-to-action.php, readme.txt, tests/test-cta.php
9.99.0.2 で記事編集ページを開くと Fix Uncaught Error をくらってしまう
wp_kses の書き間違い部分修正
* npm run phpunit
コード見ておかしくないよね？
---
* プルしたか？
* ビルドしたか？
=> 【確認中】[ CTA ] Fix Uncaught Error 

admin/admin-active-setting-page.php, readme.txt, vkExUnit.php
=> [ Change version ] 9.99.3.0 / 有効化画面で発生する Call to undefined function を修正

inc/other-widget/widget-taxonomies.php, readme.txt
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1109
- wp_dropdown_categiories に name と value_field パラメーターを追加
タグとカスタムタクソノミーでタクソノミーウィジェットが正常動作するのを確認しました。
ローカル環境
タグとカスタムタクソノミーでタクソノミーウィジェットが正常動作するのを確認お願いします。
---
* プルしたか？
* ビルドしたか？
=> 【2人目確認待ち】タクソノミーウィジェットを修正

composer.json, composer.lock, readme.txt, vkExUnit.php
https://github.com/vektor-inc/vk-blocks-pro/pull/2227
=> [ Change version ] 9.99.5.0 [ Other ] Update VK CSS Optimize 0.2.5

inc/css-customize/css-customize-single.php, readme.txt
https://wordpress.org/support/topic/%e3%83%90%e3%83%bc%e3%82%b8%e3%83%a7%e3%83%b3-9-100-2-1-%e3%81%ab%e3%81%a4%e3%81%84%e3%81%a6/#post-18130817
=> [ Bug Fix ][ CSS Customize ] Fixed an issue where CSS customizations were not applied on single page.

inc/css-customize/css-customize.php, readme.txt
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1145#event-15290787353
CSS読み込み順の調整
ローカルでお願いします（・ｗ・；
ExUnit > CSS カスタマイズに下記を記載
```
body p {
color:blue !important;
}
```
→ 公開画面側で文字が青くなる事を確認
---
* プルしたか？
* ビルドしたか？
=> [ CSS カスタマイズ ] ExUnit > CSS カスタマイズ が効かない不具合を修正

inc/css-customize/css-customize-single.php, readme.txt
https://vws.vektor-inc.co.jp/forums/topic/105149
=> [ Bug Fix ][ CSS Customize ] Fix PHP warning on the settings screen of Contact Form 7. 

.phpcs.xml, delete-old-option-meta.php, inc/other-widget/widget-taxonomies.php, inc/post-type-manager/package/class.post-type-manager.php, initialize.php, readme.txt, uninstaller.php, veu-package-manager.php, veu-packages.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1123
- PHP CS のルール設定（変数や関数・クラス名等の接頭語に関するものや不要なものを除外対象に）
- ルートディレクトリの PHP を修正
- 一部のテキストドメインが vk-blocks や vk-filter-search-pro になっていたのを修正
```
<exclude-pattern>/inc/</exclude-pattern>
<exclude-pattern>/tests/</exclude-pattern>
<exclude-pattern>/admin/</exclude-pattern>
```
- .phpcs.xml に上記ルールを追加したときに composer phpcs を実行しても ERROR が出ないのを確認しました。
- 全体を `vk-blocks` や `vk-filter-search` で検索して `__(中略)` の中身にこれらがないことを確認しました。
ローカル環境
```
<exclude-pattern>/inc/</exclude-pattern>
<exclude-pattern>/tests/</exclude-pattern>
<exclude-pattern>/admin/</exclude-pattern>
```
- .phpcs.xml に上記ルールを追加したときに composer phpcs を実行しても ERROR が出ないのを確認しました。 …
=> PHP CS のルール設定 & ルートの PHP を修正 ＆ 一部テキストドメインを修正

inc/sns/assets/_scss/_sns.scss, readme.txt
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/1159
gapが効いておらず、marginで余白を付与していたようでしたので、今後のことも考えてシンプルに実装できそうなgapで余白を調整しました。
* masterブランチで、検証ツールなどを開き、シェアボタンの余白の `gap;5;` が効いていなくて`margin:3px;` で余白をとっていることを確認して、このブランチに切り替えてnpm run build して、gapがきいていて、見た目のデザインやボタンhover時もmasterブランチのデザインと変わらないことを確認しました。
* 念の為、カスタマイズ > ExUnit 設定 > SNS 設定 の「ソーシャルボタンのスタイル設定」> 「背景なし」にチェックして「ボタンの色」は適当に色を入れて、表示上に問題ないことを確認しました。
実装者と同じ方法で確認をお願いします。
---
* プルしたか？
* ビルドしたか？
=> [ Share button ] `.veu_socialSet` コンポーネントの `gap` が要素間に適切な間隔を適用しない問題を解決しました。

inc/call-to-action/package/widget-call-to-action.php, readme.txt
=> [ 不具合修正 ][ CTA ] 404ページでCTAを表示すると発生する Warning を修正

inc/post-type-manager/package/class.post-type-manager.php, tests/test-template-tags.php
#1196 
- `is_embeddable`のロジックを専用のメソッド`is_post_type_embeddable`にリファクタリングしました。
- `is_post_type_embeddable`メソッドに対するユニットテストを追加し、保存されたメタデータに基づいて正しいブール値を返すことを確認しました。
1.  https://demo.dev3.biz/portfolio-basic/ をFTPで`inc/post-type-manager/package/class.post-type-manager.php` を`refactor/post-type-manager/is_embeddable`のコードに上書き
2. カスタム投稿タイプの設定画面で「外部サイトからの埋め込み（oEmbed）を許可しない」表示を確認し以下を設定
- `test` : チェック
- `works`: チェックはしない（デフォルト状態）
3. 外部サイトでカスタム投稿タイプのURLを埋め込んだ時に以下の動作を確認。
- `test`: 個別ページとアーカイブページのURLを編集画面に貼り付けても自動埋め込みされない 
- `works`: 個別ページとアーカイブページのURLを編集画面に貼り付けると自動埋め込みされる
https://demo.dev3.biz/portfolio-basic/ 
実装者と同じ確認を行ってください。
---
* プルしたか？
* ビルドしたか？
* npm …
=> [ 仕様変更 ][ カスタム投稿タイプ設定 ] 埋め込み設定のリファクタリングとテストを追加 

inc/meta-description.php, readme.txt
.../public_html/wp-content/plugins/vk-all-in-one-expansion-unit/inc/meta-description.php
が「既知の脅威あり」とリストアップされました
らしいので対応
=> [ Bug Fix ][ Meta Description ] Refactor meta-description.php to improve excerpt support and sanitize function

admin/admin-active-setting-page.php, readme.txt
=> [ 不具合修正 ] 言語設定が日本語以外の状態で有効化設定画面で発生するPHPエラーを修正

inc/add-body-class.php, readme.txt
https://github.com/issues/assigned?issue=vektor-inc%7Cvk-all-in-one-expansion-unit%7C1221
記事詳細ページのbodyタグに
category-id-[カテゴリーID] 
tag-id-[タグID] 
[カスタムタクソノミーslug]-id-[カスタムタクソノミーID]
の3つのクラスが付与されるようにしました。
bodyタグにクラスを付与してるだけなのでパス
X-T9とLightningで以下それぞれ確認しました。
WPの管理画面より、記事を一件投稿。
その記事にカテゴリーを付与して、bodyタグに category-id-[カテゴリーID] の形式でクラスが付与されていることを確認。
複数指定した場合、同様に複数クラスが付与される事を確認。
その記事にタグを付与して、bodyタグに tag-id-[カテゴリーID] の形式でクラスが付与されていることを確認。
複数指定した場合、同様に複数クラスが付与される事を確認。
その記事にカスタムタクソノミーを付与して、bodyタグに[カスタムタクソノミーslug]-id-[カスタムタクソノミーID]の形式でクラスが付与されていることを確認。
複数指定した場合、同様に複数クラスが付与される事を確認。
WPの管理画面より、カスタム投稿タイプの記事を一件投稿。
その記事にカスタムタクソノミーを付与して、bodyタグに[カスタムタクソノミーslug]-id-[カスタムタクソノミーID]の形式でクラスが付与されていることを確認。
複数指定した場合、同様に複数クラスが付与される事を確認。
投稿者と同様
---
* …
=> [ 機能追加 ][ bodyタグ ] 記事詳細画面のbodyタグにカテゴリー、タグ、カスタムタクソノミーで判別できるクラスを付与
